### ISSUE TITLE
请求支持blued模块

### ISSUE THREAD

**Issue by MillionZBW** [tiann/Tai-Chi#144]
## 模块名字
bluedhook
## 模块用途
类似微x，仅聊天防撤回，阻止闪照消息
## 模块版本号
模块最新版本是1.1.1，支持blued6.6.9版本
## 模块安装包
地址是https://pan.baidu.com/s/1nvZLaml#list/path=%2FBluedHook&page=1

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.2.6 能否正常使用？

**Comment by MillionZBW** [comment]
> https://github.com/tiann/Tai-Chi/releases/tag/4.2.6 能否正常使用？

可以正常使用，感谢
