### ISSUE TITLE
请求支持LuckyHooker

### ISSUE THREAD

**Issue by xiaohuang2004** [tiann/Tai-Chi#149]
## 模块名字
LuckyHooker
## 模块用途
去除一些应用的限制并删除广告
KSWEB 酷我音乐/酷我音乐HD 芒果TV MxPlayer Pro Packet Capture  Perfect Player PPTV/PPTV HD 爱奇艺/爱奇艺HD/爱奇艺PPS 腾讯视频 RootExplorer ShowJava SuperSU Pro 悟空 快点投屏 优酷(暂不支持7.0.2及更新版本)
## 模块版本号
LuckyHooker-1.1.20180304
## 模块安装包
https://pan.baidu.com/s/1slDQXop
https://github.com/wuxianlin/LuckyHooker

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.2.6
