### ISSUE TITLE
模块冲突：Riru - StorageRedirect

### ISSUE THREAD

**Issue by minamion** [tiann/Tai-Chi#176]
手机型号：XiaoMi Mix2s
ROM版本：MIUI10 9.1.23(Android 9)
Xposed模块：无
APP：太极4.2.3

问题描述：与Riru - StorageRedirect v16（https://github.com/RikkaApps/StorageRedirect-assets ）冲突 开启后无法触发 Magisk 版

其他Magisk模块：Riru - Core，Riru - LocationReportEnabler，Riru - StorageRedirect，Busybox for Android NDK

补充：已通过排除法确定只有Riru - StorageRedirect冲突

**Comment by tiann** [comment]
#222 详细讨论在这里，关掉这个。
