### ISSUE TITLE
边缘手势pro版提示模块未激活

### ISSUE THREAD

**Issue by clm0081** [tiann/Tai-Chi#198]
模块名字

Xposed edge pro

模块用途

该模块为您提供了手势控制，重点控制等智能触发器。

模块版本号

5.2.3

模块安装包

https://play.google.com/store/apps/details?id=com.jozein.xedgepro
###其他
打开后提示模块未激活

**Comment by tiann** [comment]
重启手机

**Comment by clm0081** [comment]
重启过很多次了，普通版怎么都行，pro版怎么都不行。

**Comment by chouqibao** [comment]
我也是，普通版能用，pro不能用

**Comment by tiann** [comment]
安装包提取出来给我看下？

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.2.6
