### ISSUE TITLE
7.0.3微信公众号文章打开10秒必闪退。

### ISSUE THREAD

**Issue by YurisaX** [tiann/Tai-Chi#209]
手机型号：一加5
ROM版本：氢 安卓8.1
Xposed模块：无
APP：微信7.0.3

问题描述：微信打开公众号文章，10秒左右页面必闪退，微信本体不闪退。不开模块问题依旧。只有关闭magisk太极才解决。

其他Magisk模块：

补充：

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.3.0  这版本中应该修复了，请帮忙测试下
