### ISSUE TITLE
会导致Riru及相关模块失效

### ISSUE THREAD

**Issue by Raihuen** [tiann/Tai-Chi#21]
存储重定向，开feed的模块，依靠Riru-core生效的应用都会失效

**Comment by steven7851** [comment]
太极用的epic和riru两者概念差不多，有冲突难免
反正riru也有edxposed能用，和太极两者二选一吧

**Comment by tiann** [comment]
@steven7851 epic 和 riru 不是一个东西。

太极的 magisk 模块可能和 riru 类似，**它们提供注入功能**。目前来说，太极替换 libhardware/libprocessgroup，riru 替换 memtrack。

太极使用的 epic 和 edxposed 使用的 yahfa 类似，**它们提供hook功能**。请注意，**inject** 和 ** hook**不是一个概念。

理论上，这两者可以做到不冲突的；而且内测的时候也有群友反馈过，有 riru 的模块可以用。所以我才没有关心。

**Comment by zhangxuhu** [comment]
好像是概率性失效。一加5t,Android P

**Comment by zmfang** [comment]
关闭riru，太极才会生效，应该是冲突了

**Comment by tiann** [comment]
#222
