### ISSUE TITLE
请求支持ChromePie模块

### ISSUE THREAD

**Issue by 15909290414** [tiann/Tai-Chi#211]
## 模块名字
ChromePie
## 模块用途
为Chrome添加边缘手势控制
## 模块版本号
0.7.4
## 模块安装包
[com.jt5.xposed.chromepie_v21_8b45e0.zip](https://github.com/tiann/EXposed/files/2830935/com.jt5.xposed.chromepie_v21_8b45e0.zip)

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.2.6 能否正常使用？

**Comment by 15909290414** [comment]
经过测试 可以正常使用！非常感谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: weishu <notifications@github.com>
发送时间: Monday, February 11, 2019 6:07:01 PM
收件人: tiann/Tai-Chi
抄送: 15909290414; Author
主题: Re: [tiann/Tai-Chi] 请求支持ChromePie模块 (#211)


https://github.com/tiann/Tai-Chi/releases/tag/4.2.6 能否正常使用？

―
