### ISSUE TITLE
请求在太极阴上添加应用宝hook

### ISSUE THREAD

**Issue by gundamf6** [tiann/Tai-Chi#214]
模块名字

应用宝hook

模块用途
解除应用宝隐藏的全局免流入口

模块版本号

1.0.6

模块安装包
https://pan.baidu.com/s/1RDusyUGQhTn1QfzKmjYwew
大佬貌似在太极阳里面已经允许添加应用宝hook
但是经过我的测试 在太极阴里这个模块同样可以运行(用的以前的内测版改时间测试的)
希望大佬可以在太极阴里开放这个模块
另外 新年快乐

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.2.6
