### ISSUE TITLE
求【运动模拟器】模块支持

### ISSUE THREAD

**Issue by a2212997715** [tiann/Tai-Chi#215]
## 模块名字
运动模拟器

## 模块用途
本程序通达传改加手机
传憨器的数据, 达到樵枞振动手机(刷计
步器步数的放果
## 模块版本号
2.7.2

## 模块安装包
极速下载：http://t.cn/EcG4Agg

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.2.6

**Comment by a2212997715** [comment]
感谢作者大大，可以正常使用
