### ISSUE TITLE
请求更新支持应用控制器3.0版本

### ISSUE THREAD

**Issue by luo1227135067** [tiann/Tai-Chi#220]
## 模块名字
应用控制器
## 模块版本号
3.0
## 模块更新了什么？
1.界面做了大幅度优化，标题、字体、颜色等，给用户更高的自由度去调节色彩和背景效果。
2.界面控制中新增：自定义侧栏/标题栏背景颜色、自定义侧栏背景图片。
3.设置中的夜间模式开关移动到界面控制，更新后需要重新设置。
4.杂项中的背景修改移动到界面控制，更新后需要重新设置。
5.优化网络/位置/权限控制模块。
6.侧栏应用控制器标题点击可弹出重启菜单。
7.链接 https://www.coolapk.com/apk/com.click369.controlbp

**Comment by tiann** [comment]
2.90以后的版本开了之后无限重启，还不清楚什么原因。节后再弄。

**Comment by tiann** [comment]
#272
