### ISSUE TITLE
太极面具版QQ打开图黑屏

### ISSUE THREAD

**Issue by 2310473269** [tiann/Tai-Chi#225]
手机型号：小米8青春版
ROM版本：米10安卓9点0
Xposed模块：qx和q加
APP：QQ

问题描述：现在是不经常闪退了，但始终了一段时间发现打开QQ聊天时别人发图片点击查看加载时会卡住过一会黑屏，黑屏时全免屏手势会不管用，必须用小爱同学，或者通过通知栏，点击别的软件进去后才能用全面屏加速了QQ。

其他Magisk模块：没有

补充：

**Comment by 2310473269** [comment]
还有就是在QQ里打开别的网页有时也会，比如查看QQ空间访客的网页，但不是百分百了。查看图片现在是百分百黑屏

**Comment by tiann** [comment]
使用的太极magisk版本和太极的版本分别是多少？

**Comment by 2310473269** [comment]
太极4.2.5面具v18.0

**Comment by tiann** [comment]
最新版太极应该已经解决了这个问题。
