### ISSUE TITLE
模块已经激活，但是不生效

### ISSUE THREAD

**Issue by kissunyeason** [tiann/Tai-Chi#233]
手机型号：小米8SE
ROM版本：Pixel Experience 2019-01-11
Xposed模块：所有
APP：所有

问题描述：已经显示太极阳，模块也已经勾选，手机重启很多次，但对没有任何一个模块起作用，已经尝试十多个插件，用谷歌助手的那款xposed也是同样的效果

其他Magisk模块：mm

补充：操作确保完全正确，并刷机尝试数十次

**Comment by 1536455187** [comment]
.

**Comment by panyuhang93** [comment]
试试删除所有添加的应用再添加一次

**Comment by tiann** [comment]
#303
