### ISSUE TITLE
使用了微X模块，微信闪退

### ISSUE THREAD

**Issue by xyllqzj** [tiann/Tai-Chi#24]
手机型号：小米8
ROM版本：MIUI10 9.1.17
Xposed模块：微X模块
APP：微信

问题描述：微信概率性的闪退，有时候锁屏以后收到一条微信，解锁手机微信就自动关闭。

其他 Magisk 模块：

补充：

**Comment by leo783x** [comment]
同闪退，MIUI10开发版9.1.24，小米8，微信概率性被杀后台。开了微x，qx，云村清洁工，微信斗图神器。

**Comment by tiann** [comment]
425版本是否存在此问题？

**Comment by leo783x** [comment]
> 425版本是否存在此问题？

目前还没问题
