### ISSUE TITLE
请求对【版本自定义】的支持

### ISSUE THREAD

**Issue by Gaaraly** [tiann/Tai-Chi#240]
模块名字
版本自定义

模块用途
版本自定义是一款可以用于修改任意软件的当前版本号的模块，用于禁止弹出更新提示框！

模块版本号
1.1

模块安装包
https://wpd.shouji.com.cn/cdn/soft/2017/20170328/8381255707.apk

**Comment by tiann** [comment]
只有部分支持 https://github.com/tiann/Tai-Chi/releases/tag/4.2.6

建议使用对话框取消。

**Comment by Gaaraly** [comment]
但是使用『对话框取消』的版本自定义功能后，会造成『对话框取消』的FC，以及功能失效，迫于无奈才找到此插件。
PS:太极app4.3.0
      太极模块4.2.0
      对话框取消1.6.6
