### ISSUE TITLE
magisk版安卓8.0所有模块无法使用

### ISSUE THREAD

**Issue by laowei704** [tiann/Tai-Chi#241]
手机型号：华为Nova青春版
ROM版本：was-al00 8.0.0.353(c00)
Xposed模块：所有
APP：所有

问题描述：1.正常启用模块，添加应用，尝试重启，模块都显示没有启用。2.添加应用后，只能打开一次，第二次点击列表中应用无反应。

其他Magisk模块：字体模块，mm

**Comment by tiann** [comment]
试下这个：https://github.com/tiann/Tai-Chi/releases/tag/4.2.6
