### ISSUE TITLE
绿色守护无法启用xposed特征

### ISSUE THREAD

**Issue by 0987363** [tiann/Tai-Chi#243]
太极Magisk模块版本：4.0
太极APP版本：4.2.5
手机型号：一加6t
ROM版本：9.0 氧os
Xposed模块：
Xposed模块版本：
APP及版本：绿色守护 4.5.1

问题描述：
绿色守护里显示模式为非xposed模式，启用xposed特征的时候提示xposed未安装

其他Magisk模块：无

补充：

**Comment by tiann** [comment]
把你的绿色守护安装包提取出来发给我看下？

**Comment by 0987363** [comment]
google商店下的，普通app加捐赠包的方式激活附加功能

**Comment by 0987363** [comment]
https://drive.google.com/file/d/1Np4d128skcLkeTa2uFiKqqDOf5Ea_L0K/view?usp=drivesdk

提取的

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.2.6 试下这个

**Comment by rexx0520** [comment]
最新版依然有此問題
一樣是Play Store版本
