### ISSUE TITLE
请求支持下这个模块。

### ISSUE THREAD

**Issue by 1536455187** [tiann/Tai-Chi#244]
## 模块名字
per app hacking
## 模块用途
Per App Hacking是一款应用优化工具的 Xposed模块，这个模块的作用:
1防止应用启动服务
2通过提醒来禁止或者延迟应用的自启动
3禁用唤醒锁防止程亨唤醒设备
4允许对单个应用设置代理
5允许对单个应用伪造时间格式: YYYY-MM-DDHH:MI
6限制位图
## 模块版本号
1.5
## 模块安装包
https://www.lanzous.com/i33qbeh

**Comment by tiann** [comment]
#228
