### ISSUE TITLE
关于新版微信安装

### ISSUE THREAD

**Issue by each52250** [tiann/Tai-Chi#245]
太极Magisk模块版本：无
太极APP版本：4.2.5
手机型号：华为mate10
ROM版本：EMUI 9.0.0
Xposed模块：
Xposed模块版本：
APP及版本：微信7.0.3

问题描述：
在太极-阴中 使用新版微信的时候创建应用，安装微信的时候总是显示签名不一致，导致微信增强模块失效。你在常见问题中回答过，我也多次重复尝试，并不能成功解决。

其他Magisk模块：

补充：

**Comment by tiann** [comment]
删掉系统里面的微信分身再安装。

**Comment by each52250** [comment]
> 删掉系统里面的微信分身再安装。

已经尝试删掉了系统自带的微信分身。需要把什么东西关掉？

**Comment by tiann** [comment]
具体关什么我也不清楚，我不用华为手机；反正把安全中心里面的检测之类的全关掉。

**Comment by each52250** [comment]
> 具体关什么我也不清楚，我不用华为手机;反正把安全中心里面的检测之类的全关掉。

刚才把所有检测关闭后，签名是正常了，但是微信增强模块还是失效的，里面的功能不能使用

**Comment by hjj001** [comment]
> > 具体关什么我也不清楚，我不用华为手机;反正把安全中心里面的检测之类的全关掉。
> 
> 刚才把所有检测关闭后，签名是正常了，但是微信增强模块还是失效的，里面的功能不能使用

？？
