### ISSUE TITLE
太极面具版4.2.6    q+加载不出来不出来

### ISSUE THREAD

**Issue by 2310473269** [tiann/Tai-Chi#247]
太极Magisk模块版本：4.0

太极APP版本：4.2.6

手机型号：小米8青春版

ROM版本：米10安卓9点0

Xposed模块：q加

APP：QQ

面具版本：v18.1

问题描述：邮箱下载支持base. apk+ wifi密码板块后的最新太极q+QQ中加载不出来，最新版QQ，q+1.10 和 1.12都不出来

**Comment by tiann** [comment]
并不是一进去就立马出来的，要等一段时间或者多进几次。这不是太极的问题。
