### ISSUE TITLE
去你大爷的的内置浏览器 不生效

### ISSUE THREAD

**Issue by bafflingbug** [tiann/Tai-Chi#248]
太极Magisk模块版本：4.0

太极APP版本：4.2.5-4.2.6

手机型号：ONEPLUS 5

ROM版本：H2OS 9.0.0 (Android9)

Xposed模块：去你大爷的的内置浏览器

Xposed模块版本：3.0

APP及版本：微信v7.0.3

问题描述：
无法调用系统浏览器

其他Magisk模块：
1. mm
2. 冰箱的提权插件

补充：
同时使用(仅和微信相关)xp模块有
1. 大圣净化(微信假装分享) - 生效 
2. 微信群消息助手 - 生效
3. 微信QQ防撤回 - 未测试

**Comment by tiann** [comment]
怎么测试的？

**Comment by bafflingbug** [comment]
> 怎么测试的？

忘了关Issues，装了第三方浏览器以后解决了。目前推测问题可能是默认浏览器没有设置，之前没有检查过这块。
