### ISSUE TITLE
部分其他APP向微信分享，无法唤起微信

### ISSUE THREAD

**Issue by HaleShaw** [tiann/Tai-Chi#250]
太极Magisk模块版本：
太极APP版本：4.2.5
手机型号：华为荣耀10
ROM版本：8.1.0.181
Xposed模块：
Xposed模块版本：
APP及版本：微信7.0.3

问题描述：
其他APP分享到微信，无法唤起微信，提示手机未安装微信。
四川移动掌厅，平安好车主，目前这两个APP分享链接去微信，都无法唤起微信。
夸克浏览器，Chrome浏览器分享可以唤起，暂时还没测试其他APP。
其他Magisk模块：

补充：
微信通过太极阴安装，然后优化使用的。以前直接安装的微信，在通过太极安装微信的时候卸载了。

**Comment by Jack0001** [comment]
有些app会验证微信的包签名，所以无法分享，这是太极阴的限制。

**Comment by tiann** [comment]
应该已经修复了：https://www.lanzous.com/i35wgij

**Comment by HaleShaw** [comment]
测试后还是未修复

**Comment by tiann** [comment]
你把这两个 APP 也添加到太极里面就行了

**Comment by HaleShaw** [comment]
哦哦！好的！

**Comment by HaleShaw** [comment]
添加进去，两个和微信都强行停止了，还是不行
