### ISSUE TITLE
关于新版微信安装

### ISSUE THREAD

**Issue by each52250** [tiann/Tai-Chi#257]
太极Magisk模块版本：无
太极APP版本：4.2.5
手机型号：华为mate10
ROM版本：EMUI 9.0.0
Xposed模块：
Xposed模块版本：
APP及版本：微信7.0.3

问题描述：
微信增强模块失效撤回等功能失效

其他Magisk模块：

补充：
在太极-阴中 使用新版微信的时候创建应用，安装微信的时候总是显示签名不一致，导致微信增强模块失效。你在常见问题中回答过，我也多次重复尝试，并不能成功解决。后来修改了EMUI里面的手机管家的检测及支付保护中心，签名正常通过。

**Comment by tiann** [comment]
可能是微信增强插件不支持最新的微信，建议用其他插件或者使用微信 7.0

**Comment by each52250** [comment]
好的，只能回退微信版本了

**Comment by each52250** [comment]
> 可能是微信增强插件不支持最新的微信，建议用其他插件或者使用微信7.0

好的只能，回退微信版本了
