### ISSUE TITLE
请求支持Jasi Patcher

### ISSUE THREAD

**Issue by zihanhuang** [tiann/Tai-Chi#258]
## 模块名字
Jasi Patcher

## 模块用途
JASI PATCHER is an automated patching tool for android intended to bypass restrictions in the apps & games, it includes custom patches, support patches, universal patches, offline emulation, spoof, hooks, tools and utilities.
https://jaspreetsingh.store/jasi-patcher/

作用类似lucky patcher，用于破解nds模拟器drastic。在vitrual xposed里可以完美运行。

## 模块版本号
4.6

## 模块安装包
https://jaspreetsingh.store/downloads/JP.apk

[JP.zip](https://github.com/tiann/Tai-Chi/files/2854675/JP.zip)

**Comment by tiann** [comment]
[taichi_4.3.0.1.apk.zip](https://github.com/tiann/Tai-Chi/files/2854931/taichi_4.3.0.1.apk.zip)

试下这个能否正常使用

**Comment by zihanhuang** [comment]
1.模块管理里显示暂不支持Jasi破解器
2.要应用Jasi破解器的软件在附件。这个也不支持创建应用。
PS:我的magisk模块一直有问题，我用的是太极阴。
[DraStic r2.5.1.2a.zip](https://github.com/tiann/Tai-Chi/files/2858375/DraStic.r2.5.1.2a.zip)

**Comment by tiann** [comment]
非magisk版不会支持这个

**Comment by zihanhuang** [comment]
没办法启用magisk版，装了好几遍都是阴。。
taichi 4.2 + magisk 18.1，没有其他模块。
系统是一加3T氢OS 8.0

**Comment by tiann** [comment]
[magisk-taichi-v4.2.4.zip](https://github.com/tiann/Tai-Chi/files/2859178/magisk-taichi-v4.2.4.zip)

试下这版本，或者升级 9.0

**Comment by zihanhuang** [comment]
4.2.4装上了还是阴。3T官方没有9.0，以后再试原生9.0吧。

**Comment by zihanhuang** [comment]
找了台9.0的旧机子，太极阳下 Jasi破解器 模块正常运行，多谢！

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.3.2
