### ISSUE TITLE
求适配 要你命三千 4.0版！！！

### ISSUE THREAD

**Issue by abc2209198** [tiann/Tai-Chi#261]
## 模块名字
要你命三千
## 模块版本号
4.0
## 模块更新了什么？
更新了对国际版国内版抖音和快手的去水印功能

**Comment by GaHoKwan** [comment]
国际版连装都装不上，别说支持了

**Comment by tiann** [comment]
试下这个版本，应该修复了：https://www.lanzous.com/i35wgij
