### ISSUE TITLE
玩坏模块突然不支持

### ISSUE THREAD

**Issue by NRD90M** [tiann/Tai-Chi#262]
太极Magisk模块版本：4.2
太极APP版本：4.2.9
手机型号：MI8
ROM版本：开发板
Xposed模块：玩坏
Xposed模块版本：1.7.4
APP及版本：

问题描述：我记得在4.2.5的时候｛玩坏｝这个模块是支持的，并且可以正常使用，随着太极的更新，这个模块变得不再支持，希望修复这个问题，这个模块还是挺好用的，谢谢作者。

其他Magisk模块：无

补充：无

**Comment by w4601893p** [comment]
看来的下4.2.5

**Comment by NRD90M** [comment]
内核过期啊，没法用旧版本
