### ISSUE TITLE
请求允许在太极阴上添加应用宝

### ISSUE THREAD

**Issue by gundamf6** [tiann/Tai-Chi#268]
模块名字

应用宝

模块用途
于应用宝hook合用，开启官方的免流通道

模块版本号

7.3.0

模块安装包
https://migmkt.qq.com/g/myapp/yyb-common.html?ADTAG=buy.bd.yyb01

首先谢谢大佬同意了之前允许添加应用宝Hook这个模块的请求，现在太极阴中已经可以添加应用宝hook这个模块了，但是应用宝hook需要作用于应用宝
希望大佬能够允许太极阴添加应用宝

**Comment by tiann** [comment]
应该已经修复了：https://www.lanzous.com/i35wgij
