### ISSUE TITLE
标识码问题

### ISSUE THREAD

**Issue by AlbieRWang** [tiann/Tai-Chi#273]
太极APP版本：4.3
手机型号：lg  g7n
ROM版本：p
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：点了下获取标识码，第一次有个失败的信息，电话权限给了也获取失败，然后手机就打不起电话和短信，重启后会显示Android phone停止运行

其他Magisk模块：

补充：

**Comment by tiann** [comment]
那个标识码现在没啥用了。。你别管他就行
