### ISSUE TITLE
微信斗图神器模块 不生效

### ISSUE THREAD

**Issue by superLei** [tiann/Tai-Chi#281]
太极Magisk模块版本：v18.1
太极APP版本：4.2.9
手机型号：小米8
ROM版本：miui10.0.11,  android8.1
Xposed模块：
Xposed模块版本：
APP及版本：微信7.0.0

问题描述：
1. 微信斗图神器 不生效，在微信页面点emoji不弹出页面。
2. 微x模块使用正常

其他Magisk模块：

补充：

**Comment by tiann** [comment]
请使用正确的模块版本。比如 7.0 微信用 7.0 斗图。这个问题与太极没关系。

**Comment by superLei** [comment]
软件和模块的版本没问题

**Comment by superLei** [comment]
> 请使用正确的模块版本。比如 7.0 微信用 7.0 斗图。这个问题与太极没关系。

软件和模块的版本没问题

**Comment by superLei** [comment]
![image](https://user-images.githubusercontent.com/17941039/52765355-b304b500-305e-11e9-95a8-849ba4295eb7.png)
