### ISSUE TITLE
请求更新 mdwechat 3.4.0

### ISSUE THREAD

**Issue by zhangxuhu** [tiann/Tai-Chi#282]
## 模块名字
Mdwechat
## 模块版本号
3.4.0
## 模块更新了什么？
更新内容:
1.适配微信 7.0.3
2.优化和修复了很多问题
3.求捐赠打赏！！！
4.求捐赠打赏！！！
5.求捐赠打赏！！！

下载：https://repo.xposed.info/module/com.blanke.mdwechat

**Comment by tiann** [comment]
内部已经更新，等发布就行了。

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.3.2
