### ISSUE TITLE
请求更新 抖音插件2.3.0

### ISSUE THREAD

**Issue by zhangxuhu** [tiann/Tai-Chi#283]
## 模块名字
抖音插件
## 模块版本号
3.2.0
## 模块更新了什么？
1.新增支持抖音5.0.0
2.修复视频下载bug
3.新增音频下载
4.新增长按复制视频描述
5.修复和优化其他bug
6.觉得好用的话，打赏作者两包辣条吧~

下载链接：https://repo.xposed.info/module/com.blanke.awemexposed

**Comment by tiann** [comment]
fixed
