### ISSUE TITLE
NoLitter 请求模块支持

### ISSUE THREAD

**Issue by calaquendiv** [tiann/Tai-Chi#284]
## 模块名字
NoLitter
## 模块用途
NoLitter 会将应用在根目录下乱建的文件夹统一移动至“SD卡/Android/files/”文件夹下，并重定向应用今后的读写请求，以保证SD卡根目录整洁，并尽可能不影响应用使用。
## 模块版本号
1.3.4
## 模块安装包
https://github.com/xddxdd/lantian-nolitter

**Comment by tiann** [comment]
XInternalSD 好像已经支持了，NoLitter这个看起来不错

**Comment by Cyclonekid** [comment]
@tiann 
能否XInternalSD或者NoLitter支持的时候支持成全局的，不需要将应用添加到太极内才能生效，否则的话 基本上所有的应用都要增加到太极内了·······

**Comment by calaquendiv** [comment]
> XInternalSD 好像已经支持了，NoLitter这个看起来不错

请教如何安装XInternalSD, 我从Tai-Chi内的Coolapk安装它显示不支持创建此应用

**Comment by calaquendiv** [comment]
> @tiann
> 能否XInternalSD或者NoLitter支持的时候支持成全局的，不需要将应用添加到太极内才能生效，否则的话 基本上所有的应用都要增加到太极内了·······

应用机制决定没有办法全局吧
本来也就是把不遵守文件规范的app放到XInternalSD

**Comment by Cyclonekid** [comment]
> > @tiann
> > 能否XInternalSD或者NoLitter支持的时候支持成全局的，不需要将应用添加到太极内才能生效，否则的话 基本上所有的应用都要增加到太极内了·······
> 
> 应用机制决定没有办法全局吧
> 本来也就是把不遵守文件规范的app放到XInternalSD

但测试的时候发现，我启用模块后，单独在XInternalSD内设置，不遵守文件规范的app不能在XInternalSD的应用下生效，把不遵守文件规范的app加入太极后，XInternalSD的设置才能生效。

**Comment by calaquendiv** [comment]
> > > @tiann
> > > 能否XInternalSD或者NoLitter支持的时候支持成全局的，不需要将应用添加到太极内才能生效，否则的话 基本上所有的应用都要增加到太极内了·······
> > 
> > 
> > 应用机制决定没有办法全局吧
> > 本来也就是把不遵守文件规范的app放到XInternalSD
> 
> 但测试的时候发现，我启用模块后，单独在XInternalSD内设置，不遵守文件规范的app不能在XInternalSD的应用下生效，把不遵守文件规范的app加入太极后，XInternalSD的设置才能生效。

虽然与issue无关 帮作者解释下
Tai-Chi的用途就是给装Tai-Chi里面的app挂载xposed模块
XInternalSD要全局生效，你得装真Xposed或者不靠模块只靠root的Storage Redirect

**Comment by tiann** [comment]
1. Nolitter: 试下这个版本是否可用：https://www.lanzous.com/i35wgij
2. 是否需要开发全局模式还有待商榷。

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.3.5
