### ISSUE TITLE
淘宝无法正常使用

### ISSUE THREAD

**Issue by mapleshadow** [tiann/Tai-Chi#286]
太极Magisk模块版本：最新
太极APP版本：最新
手机型号：一加6T
ROM版本：9.0.11
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：如题，一旦点击淘宝内我的菜单，就报错，一长串错误………

其他Magisk模块：淘饭饭

补充：

**Comment by tiann** [comment]
淘饭饭模块的问题吧？
