### ISSUE TITLE
请求模块更新

### ISSUE THREAD

**Issue by ABCxiaoxu** [tiann/Tai-Chi#290]
太极Magisk模块版本：4.5.0

太极APP版本：4.3.0

手机型号：Pixel 2 XL

ROM版本：Android9.0

Xposed模块：MDWechat

APP：微信

Xposed模块版本：3.4.0

APP及版本：微信7.0.3

问题描述：请就太极更新适配MDWechat3.4.0，谢了！

**Comment by tiann** [comment]
#282
