### ISSUE TITLE
模拟位置提示未在xp中启用，没法用

### ISSUE THREAD

**Issue by HaleShaw** [tiann/Tai-Chi#292]
太极Magisk模块版本：4.5.0
太极APP版本：4.30
手机型号：荣耀10
ROM版本：8.1
Xposed模块：模拟位置
Xposed模块版本：1.2.681.1701
APP及版本：

问题描述：在太极阳里面启用了模块，给了模块所有权限，打开模块的时候还是提示未在XP中启用。确定后就退出了，没法用。

其他Magisk模块：

补充：

**Comment by tiann** [comment]
9.0 才支持。

**Comment by HaleShaw** [comment]
后续会适配8.1吗？

**Comment by tiann** [comment]
不会
