### ISSUE TITLE
请求支持验证码提取器模块

### ISSUE THREAD

**Issue by Cyclonekid** [tiann/Tai-Chi#293]
## 模块名字
验证码提取器(Xposed)
## 模块用途
· 收到验证码短信后将验证码复制到系统剪贴板
· 当验证码被复制后显示Toast
· 自定义验证码短信关键字（正则表达式）
· 自定义短信验证码匹配规则，并支持导入导出
· 自动尝试输入验证码
· 验证码短信标记为已读（实验性）
· 验证码短信删除（实验性）
## 模块版本号
V 1.5.6
## 模块安装包
https://www.coolapk.com/apk/com.github.tianma8023.xposed.smscode

**Comment by tiann** [comment]
#44
