### ISSUE TITLE
请求更新qq净化3.3.7

### ISSUE THREAD

**Issue by zhangxuhu** [tiann/Tai-Chi#294]
## 模块名字
QQ净化
## 模块版本号
3.3.7
## 模块更新了什么？
重写了大部分代码
删除部分不必要功能
添加了一些新功能
支持 QQ 7.9.8
情人节快乐
下载链接:
https://github.com/zpp0196/QQPurify/releases/tag/3.3.7

**Comment by tiann** [comment]
https://github.com/tiann/Tai-Chi/releases/tag/4.3.2
