### ISSUE TITLE
建议适当放宽模块版本限制

### ISSUE THREAD

**Issue by zhangxuhu** [tiann/Tai-Chi#295]
太极Magisk模块版本：4.5.0
太极APP版本：4.3.0
手机型号：Oneplus 5T
ROM版本：P
Xposed模块：qx
Xposed模块版本：2
APP及版本：2

问题描述：
另外大佬是否考虑适当放宽模块版本限制？
其他Magisk模块：
无
补充：

我想到的几种可能的方案，欢迎大家讨论
1.针对已经明确适配太极的模块(模块中可以显示已经通过太极激活)的，放宽全部版本限制
2.针对已经兼容太极的模块，可以放宽小版本号限制，如3.3.x都兼容，3.4.1不兼容。
3.可以采取动态更新策略，从服务器上动态拉取支持的模块（我可以提供服务器）。

**Comment by xiuluo** [comment]
赞同，比如qq净化这个模块，作者已经明确支持太极，所以我觉得可以不用限制这类模块的版本号了。

**Comment by cjjdaq** [comment]
是呀，一些模块已经主动兼容太极了。为何还要弄诸多限制？

**Comment by bafflingbug** [comment]
将1改为限制最低版本比较好

**Comment by tiann** [comment]
严格限制对开发者而言的好处在于：不用害怕破解。

Xposed 插件无法加固，Java层混淆基本没什么用，用 C 写又费时费力。明确使用收费机制开启高级功能的插件最终都会死于破解，到最后开发者弃坑。

所以不论你们用户怎么看，这我不会改。
