### ISSUE TITLE
MDWechat  3.4.0更新

### ISSUE THREAD

**Issue by zuowangzuowang** [tiann/Tai-Chi#296]
## 模块名字
MDWechat
## 模块版本号
3.4.0
## 模块更新了什么？
1.适配微信 7.0.3
2.优化和修复了很多问题

下载地址:https://repo.xposed.info/module/com.blanke.mdwechat

**Comment by tiann** [comment]
提问题之前先看看存不存在这个问题。明明昨天半夜已经修复了。
