### ISSUE TITLE
太极勾选模块后无法开机

### ISSUE THREAD

**Issue by FC-Cccc** [tiann/Tai-Chi#301]
太极Magisk模块版本：V4.2.0
太极APP版本：定海神针·4.3.2
手机型号：OnePlus A6000
ROM版本：OP6_H2_BETA_15
Xposed模块：QQ净化  微X模块  音量增强器  云村清洁工  指纹支付  核心破解  运动修改器
Xposed模块版本：均为太极最新兼容版本
APP及版本：微信7.0.3   QQ7.9.8   支付宝10.1.55.6000   网易云音乐5.9.0

问题描述：勾选Xposed模块重启后卡开机动画，删除/data/system/taichi/modules.list后才可正常开机
在太极再次勾选模块重启后，仍出现以上情况

其他Magisk模块：Audio Compatibility Patch    Audio Modification Libarary    VIPER4Android FXv3.4
                              宁静之雨苹方字体13.0d1e3               Android Universal Optmization

补充：Rom是一加6公测15版  Magisk版本18.1

**Comment by tiann** [comment]
#280 

关闭其他所有 magisk 模块再做尝试。
