### ISSUE TITLE
微信小程序闪退

### ISSUE THREAD

**Issue by linshouwen** [tiann/Tai-Chi#302]
太极Magisk模块版本：4.0
太极APP版本：4.29
手机型号：redmi note4x
ROM版本：MIUI10 7.0 
Xposed模块：
Xposed模块版本：
APP及版本:谷歌版微信7.0

问题描述：
微信添加进太极里，打开小程序，小程序会闪退，移除后可正常打开微信小程序
其他Magisk模块：

补充：

**Comment by tiann** [comment]
升级到最新版太极
