### ISSUE TITLE
太极阳已启用，模块不生效

### ISSUE THREAD

**Issue by ezhhaiy0** [tiann/Tai-Chi#303]
太极Magisk模块版本：4.2.0
太极APP版本：4.3.0
手机型号：荣耀10
ROM版本：EMUI 8.1
Xposed模块：微X模块、MDWechat
Xposed模块版本：微X模块1.25、MDWechat3.3.0
APP及版本：微信7.0.0（谷歌市场版）、微信6.2.2（谷歌市场版）

问题描述：官方rom，太极阴可正常使用。启用太极阳后，模块失效；转回太极阴，模块又生效。

其他Magisk模块：无

补充：MM管理器6.1.0、7.0.0及Magisk 18.0、18.1都试过，结果一样。
请weishu帮助看一下，谢谢

**Comment by tiann** [comment]
重新添加应用，重新勾选模块
