### ISSUE TITLE
音量增强器不生效：模块没能成功hook

### ISSUE THREAD

**Issue by mr-cn** [tiann/Tai-Chi#306]
太极Magisk模块版本：none
太极APP版本：4.2.5
手机型号：Xiaomi 6
ROM版本：MIUI 9.6 based on Android 8
Xposed模块：音量增强器
Xposed模块版本：0.0.30(模块下载中提供的0.0.29同样失效，应该与版本无关)
APP及版本：网易云音乐 5.9&5.8.3&5.9.0

问题描述：

**普通模式，非Magisk！**

## 上周(19/2/10)

安装网易云音乐5.9（内测版）+音量增强器0.0.29，工作一切正常

## 今天（19/2/16）

发现之前安装的是内测版云音乐，已经失效，无法使用，遂在**MIUI的应用管理**通过系统卸载网易云音乐
*没使用太极自己的卸载按钮，不知道是不是与这个有关*

安装正式版的云音乐5.9版本（官方2/15发布的），发现音量增强失效，模块内显示已通过太极激活。

尝试过清除应用和模块的数据并卸载5.9，重装5.8.x版本，同样无效。

**在某一次尝试中，发现有意思的一点是，我没通过太极安装网易云音乐，而是直接从系统安装，太极竟然将其列入了应用列表，并显示云音乐的内核需要升级（从70还是90 升级到 122），其他应用正常**
*很奇怪，为什么全新安装的会识别出内核呢*

我认为可以判定此问题与云音乐和模块的版本都无关。

---

在晚上，我把bin456789/Unblock163MusicClient-Xposed的源码下下来自己debug，在Mi 6上调试，发现与hook相关的代码并没有工作：随便下了几个断点，都没有命中。但是模块的UI部分，断点正常命中。

![snipaste_2019-02-16_23-15-59](https://user-images.githubusercontent.com/19818121/52901616-dc7d3680-3240-11e9-9353-d68a94e92ed8.jpg)

![snipaste_2019-02-16_23-21-22](https://user-images.githubusercontent.com/19818121/52901686-9eccdd80-3241-11e9-954a-6b79e65dbad3.jpg)

不过我自己此前从没接触过android开发，idea也是刚下的，不知道在xposed中这样下断点能不能中。但我猜测跟这有关。

其他Magisk模块：

none

补充：

PS：另一个模块，云村清洁工，部分功能正常：去广告的大部分正常，模拟会员不能正常使用。在出问题之前，在同样的云音乐版本上，会员功能是可以用的。

PPS: 既然第一次安装时工作正常，如果可以提供一个流程，彻底移除之前留下的痕迹，然后重新创建并优化，按道理讲也是能工作的。

PPPS: 这个机器人有点烦人了。能到github上说明问题的，基本的语言能力还是有吧。还close就算了

**Comment by mr-cn** [comment]
如果需要提供其他信息，请说明

**Comment by tiann** [comment]
0. 尝试下这个版本 https://www.lanzous.com/i35wgij  支持 0.0.30 
1. 除非作者本人，其他人 build 的源码产生的安装包无法在太极中被加载。
2. 能到github上说明问题的，也有很多什么信息都不提供的，而且占绝大多数；你去看看被机器人 close 的 issue 里面就知道了。

**Comment by mr-cn** [comment]
更新太极版本情况依旧。
0.0.30作者没有发布，是master分支build出来的，既然没有被加载的话，情况依旧是理所当然的。
我等下换回official build试一下。
所以说，遇到这种情况，我们也没有办法自己尝试解决了…🤔

**Comment by mr-cn** [comment]
使用网易云音乐5.8.3和太极中提供的音量模块2.6.2再次测试，依旧不能正常工作。

**Comment by tiann** [comment]
作者已经发布了  0.0.30 ，是用作者发布的尝试。

**Comment by mr-cn** [comment]
刚看到是才发布的0.0.30。

不过现在还是一头雾水，不清楚是什么出了问题。

**Comment by mr-cn** [comment]
0.0.30在网易云5.8.3上工作正常。
不敢更新到5.9了，怕他又出问题。

**Comment by tiann** [comment]
如果是更新导致的 SELinux 问题，只需要重新安装，然后勾选模块就OK了。
