### ISSUE TITLE
申请适配最新Xposed edge Pro v5.3版

### ISSUE THREAD

**Issue by abc2209198** [tiann/Tai-Chi#309]
## 模块更新了什么？

链接:https://pan.baidu.com/s/1bAWp5PuBwIu9L7aTxYMUJA 提取码:3m15

**Comment by tiann** [comment]
请等待明天的  Daily Build

**Comment by caliban511** [comment]
我这里也是，一觉醒来PLAY自动更新用不了了。。。

**Comment by tiann** [comment]
4.3.5.3 已修复，公众号去下载 Daily Build 版。
