### ISSUE TITLE
普通最新4.3.5版钉钉打卡不能正常使用

### ISSUE THREAD

**Issue by maliangjie** [tiann/Tai-Chi#313]
## 模块名字
钉钉打卡

## 模块版本号
4.1.0

## 模块更新了什么？
打卡app不能打开位置模拟，会提示xposed未激活。所以依然是不能用的。而且也不支持把打卡app太极一下。

**Comment by tiann** [comment]
magisk版正常使用，普通版需要联系作者修改。
