### ISSUE TITLE
QQ净化3.3.7有效，3.4.0不生效

### ISSUE THREAD

**Issue by jiastku98** [tiann/Tai-Chi#316]
手机型号：小米Mix3
ROM版本：Miui10 9.0
Xposed模块：QQ净化
APP：QQ7.9.8

问题描述：
QQ净化3.3.7时候可以使用，升级到3.4.0就无法生效任何功能，但是QQ净化识别了太极激活

其他Magisk模块：
MM

其他Xposed模块：
QX
微X
核心破解
音量增强器
云村清洁工

**Comment by jiastku98** [comment]
已经尝试过重启手机，重装apk，重新应用

**Comment by tiann** [comment]
4.3.5.3 已修复，公众号去下载 Daily Build 版。

**Comment by Dawnwalker666** [comment]
QQ净化已经不适用于新版本QQ8.8.23了，望更新修复 @tiann

**Comment by tiann** [comment]
你找错人了
