### ISSUE TITLE
Magisk版重启出现"null 状态异常，点击处理“

### ISSUE THREAD

**Issue by yiyang-cn** [tiann/Tai-Chi#321]
太极Magisk模块版本：v4.5.0
太极APP版本：v4.3.5
手机型号：xiaomi 5
ROM版本：MIUI 10.8.11.22(Android 8.0.0)
Xposed模块：AcEnergy2 V1.5.0，应用控制器V2.8.9，运动加速器v1.6.1
Xposed模块版本：
APP及版本：支付宝10.1..55.6000

问题描述：太极.magisk安装好后能正常使用，但是重启后变成太极.阴且出现"null 状态异常，点击处理“，再次重启后有时能恢复正常。

其他Magisk模块：无

补充：若多次重启还是不能恢复正常时只有卸载太极后重装

**Comment by Dark-Existed** [comment]
试一下软重启

**Comment by yiyang-cn** [comment]
> 软重启

是指的不重启系统？把太极app重启一下?这个方法试过不行，只有重启系统才行。
有几次重启系统也没恢复，目前没找到规律。
在能正常使用的情况下，只要重启系统，必然会出现“null状态异常，点击处理”错误

**Comment by Dark-Existed** [comment]
> > 软重启
> 
> 是指的不重启系统？把太极app重启一下?这个方法试过不行，只有重启系统才行。
> 有几次重启系统也没恢复，目前没找到规律。
> 在能正常使用的情况下，只要重启系统，必然会出现“null状态异常，点击处理”错误

木函 软重启

**Comment by tiann** [comment]
#288
