### ISSUE TITLE
当网络不好时候或者无网络，微信狂闪退

### ISSUE THREAD

**Issue by 06ji** [tiann/Tai-Chi#35]
手机型号：小米5
ROM版本：miui10 8.10.12
Xposed模块：微X模块
APP：微信

问题描述：当网络不好时候或者无网络，微信狂闪退

其他 Magisk 模块：MM管理器

补充：

**Comment by tiann** [comment]
跟网络有关吗？

**Comment by 06ji** [comment]
> 跟网络有关吗？

不清楚，好像是点开微信里面的微信模块，然后按主页键，开始闪退，不过你的4.1.5好像解决了，辛苦了

**Comment by 06ji** [comment]
> 跟网络有关吗？

应该是，我刚再次测试，把wifi和数据关了，点开微信里面的微信模块，然后按主页键，开始闪退

**Comment by tiann** [comment]
4.0 版本是否有此问题？
