### ISSUE TITLE
v3.3b会导致开不了Wifi

### ISSUE THREAD

**Issue by lebronbiann** [tiann/Tai-Chi#48]
版本，v3.3b
手机，miui10小米6安卓8，
bug，会导致打不开Wifi，打开搜不到Wifi，瞬间关闭，设置和系统桌面停止运行。

**Comment by tiann** [comment]
待确认

**Comment by lebronbiann** [comment]
这个版本还是不行，Wifi打开就给关闭了

**Comment by tiann** [comment]
[magisk-taichi-v3.5-b.zip](https://github.com/tiann/EXposed/files/2791693/magisk-taichi-v3.5-b.zip)

再看看这个是否解决？

**Comment by tiann** [comment]
4.0 版本 是否有此问题？

**Comment by y3wegy** [comment]
我也遇到了，我是国际版
