### ISSUE TITLE
概率性睡死

### ISSUE THREAD

**Issue by PowerDi** [tiann/Tai-Chi#57]
手机型号：Xiaomi note3
ROM版本：Pixel experience P/Syberia P
Xposed模块：微信增强、指纹支付、
APP：未知

问题描述：太极4.1.5版本，3.3b的magisk模块，装有绿色守护/黑域/冰箱，息屏待机一段较长的时间后，应用到太极中的微信能够打开应用，但未添加到太极里的应用/系统应用均卡死在第一屏且无法通过点击“强行停止应用”来停止，点击后该按键仍然是enabled的，由于不会提示崩溃，所以不知道这种情况下是否能够获取到log

其他 Magisk 模块：

补充：

**Comment by zhangxuhu** [comment]
手机型号：ONEPLUS 5T
ROM版本：Hydrogen OS P

一加5t也发生过一次，打不开应用也无法强行停止，只能重启。也装有黑域。

**Comment by tanranran** [comment]
+1

手机型号：Red MI Note7
ROM版本：MIUI10
Xposed模块：微信增强、蚂蚁森林、

并且只能通过重启解决

**Comment by tiann** [comment]
是否黑域了 太极 ？

**Comment by Jack0001** [comment]
同样发生了睡死状况，软重启后卡解锁界面，正如维术大佬所说的一样黑阈了太极，现在去除黑阈清单后测试中。

**Comment by tiann** [comment]
@Jack0001  测试结果如何？

**Comment by tanranran** [comment]
@tiann 亲测是黑域的锅，已经稳定使用20多天了

**Comment by tiann** [comment]
好的，那我在使用说明上加上 **不要黑域太极**，然后 close 这个问题了。谢谢反馈。
