### ISSUE TITLE
会支持magisk16.6吗？

### ISSUE THREAD

**Issue by lion1991** [tiann/Tai-Chi#8]
有一些机型例如mi8se 只能用16的版本但是咱们模块有限制，以后会考虑支持吗？谢谢

**Comment by tiann** [comment]
[Magisk-TaiChi-v3.9-B-For-MI8SE.zip](https://github.com/tiann/Tai-Chi/files/2882773/Magisk-TaiChi-v3.9-B-For-MI8SE.zip)

已经有第三方做出兼容包，直接使用即可。
