### ISSUE TITLE
bug反馈：有的APP使用微信支付提示“未安装微信”或者无法调用微信支付？你在常见问题里回答过，但是无法在创建里找到这个APP

### ISSUE THREAD

**Issue by banzuan** [tiann/Tai-Chi#94]
手机型号：meizu PRO7
ROM版本：Flyme 7.2.0.0A
Xposed模块：
APP：微店、密码键盘

问题描述：有的APP使用微信支付提示“未安装微信”或者无法调用微信支付？你在常见问题里回答过，但是无法在创建里找到这个APP

其他Magisk模块：

补充：

**Comment by DaFeiMao233** [comment]
截图我们看看，你确定是太极吗？

**Comment by fanxl666** [comment]
Magsik版太极，太极·阳是没有这个问题的，你用的是普通版太极吧，就是太极·阴

**Comment by banzuan** [comment]
> Magsik版太极，太极·阳是没有这个问题的，你用的是普通版太极吧，就是太极·阴

是的，我用的是太极.阴

**Comment by banzuan** [comment]
> 截图我们看看，你确定是太极吗？

是太极

**Comment by robert53850** [comment]
太极阳根本不会重新创建APP，也不重新签名，就不会出现“分享提示未安装”的问题，这个只会在太极阴出现。

**Comment by tiann** [comment]
普通版太极的话，等待下一个版本。

**Comment by tiann** [comment]
fixed https://github.com/tiann/Tai-Chi/releases/tag/4.2.6

**Comment by banzuan** [comment]
> fixed https://github.com/tiann/Tai-Chi/releases/tag/4.2.6

手机型号：meizu PRO7
ROM版本：Flyme 7.2.0.0A
Xposed模块：
APP：转转

问题描述：有的APP使用微信支付提示“未安装微信”或者无法调用微信支付？你在常见问题里回答过，但是无法在创建里找到这个APP
